
services:
  app:
    build: .
    container_name: laravel_app
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel
    restart: unless-stopped
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - laravel
    restart: unless-stopped
    ports:
      - "6379:6379"

networks:
  laravel:
    driver: bridge

 


  app:
    ports:
      - "80:8000"