version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - redis
    env_file:
      - .env

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    restart: always
    # Define o diretório de trabalho para que o 'artisan' seja encontrado
    working_dir: /var/www
    command: php artisan queue:work
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: always
    networks:
      - laravel

  echo:
  image: node:18-alpine
  container_name: laravel_echo
  working_dir: /var/www
  restart: always
  volumes:
    - .:/var/www
    - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
  # A sintaxe do comando foi corrigida para usar o script de espera corretamente
  command: /bin/sh -c "/usr/local/bin/wait-for-it.sh laravel_redis:6379 -- npx laravel-echo-server start"
  ports:
    - "6001:6001"
  networks:
    - laravel
  depends_on:
    - redis

networks:
  laravel:
    driver: bridge