version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - redis
    env_file:
      - .env

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    restart: always
    working_dir: /var/www
    command: php artisan queue:work
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: always
    networks:
      - laravel

  echo:
    image: node:18-alpine
    container_name: laravel_echo
    working_dir: /var/www
    restart: always
    volumes:
      - .:/var/www
      # O script 'wait-for-it.sh' deve estar em um caminho acessível no PATH do container, ou ser referenciado com um caminho absoluto
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    # O comando foi corrigido para usar a sintaxe correta do shell
    command: /bin/sh -c "/usr/local/bin/wait-for-it.sh laravel_redis:6379 --timeout=30 -- npx laravel-echo-server start"
    ports:
      - "6001:6001"
    networks:
      - laravel
    depends_on:
      - redis

networks:
  laravel:
    driver: bridge