version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - redis
    env_file:
      - .env

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    restart: always
    command: php artisan queue:work
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: always
    networks:
      - laravel

  echo:
    image: node:18-alpine
    container_name: laravel_echo
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    command: npx laravel-echo-server start
    ports:
      - "6001:6001"
    networks:
      - laravel
    depends_on:
      - redis

networks:
  laravel:
    driver: bridge
