services:
  nginx:
    ports:
      - "8000:80"

  mysql:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"

  npm:
    image: node:18
    container_name: laravel_npm
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: npm run dev 
    networks:
      - laravel
    depends_on:
      - app
