services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app 
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_started
    # Variáveis lidas do .env
    env_file:
      - .env

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    restart: always
    working_dir: /var/www
    command: php artisan queue:work
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_started
    # Variáveis lidas do .env
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/conf:/etc/letsencrypt
    networks:
      - laravel
      - jitsi
    depends_on:
      app:
        condition: service_started

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $!; done"

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: always
    networks:
      - laravel

  laravel_echo:
    image: node:18-alpine
    container_name: laravel_echo
    working_dir: /var/www
    restart: on-failure
    volumes:
      - .:/var/www
      - ./docker/certbot/conf:/etc/letsencrypt:ro
    command: ["/bin/sh", "-c", "apk add --no-cache netcat-openbsd && while ! nc -z laravel_redis 6379; do echo 'Waiting for Redis...'; sleep 2; done && echo 'Redis is ready!' && npx laravel-echo-server start --force --no-daemon"]

    ports:
      - "6001:6001"
    networks:
      - laravel
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env


  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

# ----------------- NOVO - SERVIÇOS JITSI MEET -----------------
  # ----------------- JITSI MEET SERVICES -----------------
  web:
    image: jitsi/web:stable
    restart: always
    networks:
      jitsi:
        aliases:
          - jitsi.sosmulherreal.com
    volumes:
      - ./jitsi/web/config:/config:Z
    environment:
      - JITSI_DOMAIN=jitsi.sosmulherreal.com
      - ENABLE_HTTPS=0
      - DOCKER_HOST_ADDRESS=72.60.184.186
      - JVB_HOSTNAME=jitsi.sosmulherreal.com
      - JICOFO_HOSTNAME=jitsi.sosmulherreal.com
      - JICOFO_AUTH_PASSWORD=jitsi_jicofo_auth_2024_secure
      - JVB_AUTH_PASSWORD=jitsi_jvb_auth_2024_secure
      - JIGASI_XMPP_PASSWORD=jitsi_jigasi_auth_2024_secure
    depends_on:
      - jicofo

  jvb:
    image: jitsi/jvb:stable
    restart: always
    networks:
      jitsi:
        aliases:
          - jitsi.sosmulherreal.com
    ports:
      - "10000:10000/udp"
      - "4443:4443"
    volumes:
      - ./jitsi/jvb/config:/config:Z
    environment:
      - JVB_ADVERTISE_IPS=72.60.184.186
      - JVB_HOSTNAME=jitsi.sosmulherreal.com
      - JICOFO_HOSTNAME=jitsi.sosmulherreal.com
      - JITSI_DOMAIN=jitsi.sosmulherreal.com
      - JICOFO_AUTH_PASSWORD=jitsi_jicofo_auth_2024_secure
      - JVB_AUTH_PASSWORD=jitsi_jvb_auth_2024_secure
      - JIGASI_XMPP_PASSWORD=jitsi_jigasi_auth_2024_secure
    depends_on:
      - jicofo

  prosody:
    image: jitsi/prosody:stable
    restart: always
    networks:
      jitsi:
        aliases:
          - jitsi.sosmulherreal.com
    volumes:
      - ./jitsi/prosody/config:/config:Z
    environment:
      - JITSI_DOMAIN=jitsi.sosmulherreal.com
      - JICOFO_AUTH_PASSWORD=jitsi_jicofo_auth_2024_secure
      - JVB_AUTH_PASSWORD=jitsi_jvb_auth_2024_secure
      - JIGASI_XMPP_PASSWORD=jitsi_jigasi_auth_2024_secure

  jicofo:
    image: jitsi/jicofo:stable
    restart: always
    networks:
      jitsi:
        aliases:
          - jitsi.sosmulherreal.com
    volumes:
      - ./jitsi/jicofo/config:/config:Z
    environment:
      - JITSI_DOMAIN=jitsi.sosmulherreal.com
      - JICOFO_AUTH_PASSWORD=jitsi_jicofo_auth_2024_secure
      - JVB_AUTH_PASSWORD=jitsi_jvb_auth_2024_secure
      - JIGASI_XMPP_PASSWORD=jitsi_jigasi_auth_2024_secure
    depends_on:
      - prosody

networks:
  laravel:
    driver: bridge
  jitsi:
    driver: bridge

volumes:
  mysql_data:
    driver: local
