services:
  app:
    build: .
    container_name: laravel_app
    env_file:
      - .env.${APP_ENV}
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    command: >
      sh -c "
        if [ -z \"$$(grep APP_KEY= /var/www/.env | cut -d '=' -f2)\" ]; then
          php artisan key:generate --force;
        fi &&
        php artisan optimize:clear &&
        php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - laravel
    restart: unless-stopped

  queue:
    build: .
    container_name: laravel_queue
    command: php artisan queue:work --timeout=60
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - app
      - redis
    restart: unless-stopped

  echo:
    image: node:18
    container_name: laravel_echo
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: >
      sh -c "npm install -g laravel-echo-server &&
             laravel-echo-server start --config=/var/www/laravel-echo-server.json"
    ports:
      - "6001:6001"
    networks:
      - laravel
    depends_on:
      - redis
      - app
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
