version: "3.9"

services:
  app:
    build: .
    container_name: laravel_app
    env_file:
      - .env.${APP_ENV}   # escolhe dev ou prod automaticamente
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    command: >
      sh -c "
        if [ -z \"$$(grep APP_KEY= /var/www/.env | cut -d '=' -f2)\" ]; then
          php artisan key:generate --force;
        fi &&
        $(if [ "$APP_ENV" = "dev" ]; then echo 'php artisan migrate:fresh --seed &&'; fi) 
        php artisan optimize:clear &&
        php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - $([ "$APP_ENV" = "dev" ] && echo "8000:80" || echo "80:80")
      - $([ "$APP_ENV" = "prod" ] && echo "443:443" || echo "")
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - $([ "$APP_ENV" = "dev" ] && echo "3306:3306" || echo "")
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - $([ "$APP_ENV" = "dev" ] && echo "6379:6379" || echo "")
    networks:
      - laravel
    restart: unless-stopped

  queue:
    build: .
    container_name: laravel_queue
    command: php artisan queue:work --timeout=60
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - app
      - redis
    restart: unless-stopped

  npm:
    image: node:18
    container_name: laravel_npm
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - $([ "$APP_ENV" = "dev" ] && echo "5173:5173" || echo "")
    command: $([ "$APP_ENV" = "dev" ] && echo "npm run dev" || echo "sleep infinity")
    networks:
      - laravel
    depends_on:
      - app

  echo:
    image: node:18
    container_name: laravel_echo
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: >
      sh -c "npm install -g laravel-echo-server &&
             laravel-echo-server start --config=/var/www/laravel-echo-server.json"
    ports:
      - "6001:6001"
    networks:
      - laravel
    depends_on:
      - redis
      - app
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
