version: "3.9"

services:
  app:
    build: .
    container_name: laravel_app
    env_file:
      - .env.dev
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    command: >
      sh -c "
        if [ ! -f /var/www/.env ]; then
          cp /var/www/.env.dev /var/www/.env
        fi &&
        php artisan config:clear &&
        php artisan cache:clear &&
        php artisan config:cache &&
        php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app
    restart: unless-stopped 
    expose:
      - "80"

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root123
    networks:
      - laravel
    restart: unless-stopped
    expose:
      - "3306"

  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - laravel
    restart: unless-stopped
    expose:
      - "6379"

  queue:
    build: .
    container_name: laravel_queue
    command: php artisan queue:work --timeout=60
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - app
      - redis
    restart: unless-stopped

  echo:
    image: node:18
    container_name: laravel_echo
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: >
      sh -c "npm install -g laravel-echo-server &&
             laravel-echo-server start --config=/var/www/laravel-echo-server.json"
    networks:
      - laravel
    depends_on:
      - redis
      - app
    restart: unless-stopped
    expose:
      - "6001"

networks:
  laravel:
    driver: bridge
